--
-- Create Schema Script 
--   Database Version   : 11.2.0.1.0 
--   TOAD Version       : 9.0.1.8 
--   DB Connect String  : TESTE 
--   Schema             : ARTBOX 
--   Script Created by  : PORTAL 
--   Script Created at  : 03/12/2020 16:31:52 
--   Physical Location  :  
--   Notes              :  
--

-- Object Counts: 
--   Indexes: 7         Columns: 12         
--   Tables: 8          Columns: 51         Constraints: 17     


CREATE TABLE ATB_REQUISICAO_ITEM
(
  NUM_REQUISICAO  NUMBER(7)                     NOT NULL,
  NUM_ITEM        NUMBER(5)                     NOT NULL,
  SEQ_MATERIAL    NUMBER(10)                    NOT NULL,
  QTD_MATERIAL    NUMBER(7,2)                   NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ATB_NOTA_ENTRADA_ITEM
(
  SEQ_FORNECEDOR  NUMBER(9)                     NOT NULL,
  NUM_NOTA        NUMBER(7)                     NOT NULL,
  SEQ_ITEM        NUMBER(3)                     NOT NULL,
  SEQ_MATERIAL    NUMBER(10)                    NOT NULL,
  QTD_ITEM        NUMBER(5,2)                   NOT NULL,
  VAL_UNITARIO    NUMBER(10,2)                  NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ATB_FORNECEDOR_ENDERECO
(
  SEQ_FORNECEDOR   NUMBER(9)                    NOT NULL,
  DM_TPO_ENDERECO  NUMBER(1)                    NOT NULL,
  SEQ_LOGRADOURO   NUMBER                       NOT NULL,
  NUM_ENDERECO     NUMBER(12)                   NOT NULL,
  NOM_COMPLEMENTO  VARCHAR2(20 BYTE),
  NUM_CEP          NUMBER(8)                    NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ATB_REQUISICAO
(
  NUM_REQUISICAO  NUMBER(7)                     NOT NULL,
  DSC_REQUISICAO  VARCHAR2(60 BYTE)             NOT NULL,
  DAT_REQUISICAO  DATE                          NOT NULL,
  NOM_USUARIO     VARCHAR2(30 BYTE)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ATB_NOTA_ENTRADA
(
  SEQ_FORNECEDOR  NUMBER(9)                     NOT NULL,
  NUM_NOTA        NUMBER(7)                     NOT NULL,
  DAT_COMPRA      DATE                          NOT NULL,
  VAL_COMPRA      NUMBER(10,2)                  NOT NULL,
  NOM_USUARIO     VARCHAR2(20 BYTE)             NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ATB_MATERIAL
(
  SEQ_MATERIAL       NUMBER(10)                 NOT NULL,
  NOM_MATERIAL       VARCHAR2(40 BYTE)          NOT NULL,
  DM_UNIDADE_MEDIDA  VARCHAR2(2 BYTE)           NOT NULL,
  QTD_MINIMO         NUMBER(7,2)                NOT NULL,
  QTD_MAXIMO         NUMBER(7,2)                NOT NULL,
  QTD_ESTOQUE        NUMBER(7,2),
  VAL_ESTOQUE        NUMBER(10,2),
  DAT_CADASTRO       DATE                       NOT NULL,
  NOM_USUARIO        VARCHAR2(20 BYTE)          NOT NULL,
  IMG_MATERIAL       VARCHAR2(40 BYTE),
  DMN_FL_BLOQ        VARCHAR2(1 BYTE)           DEFAULT 'N'                   NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ATB_FORNECEDOR
(
  SEQ_FORNECEDOR    NUMBER(9)                   NOT NULL,
  NUM_CNPJ          NUMBER(14)                  NOT NULL,
  NOM_RAZAO_SOCIAL  VARCHAR2(40 BYTE)           NOT NULL,
  NOM_FANTASIA      VARCHAR2(40 BYTE),
  NOM_CONTATO       VARCHAR2(40 BYTE),
  NUM_TELEFONE      NUMBER(14),
  NOM_USUARIO       VARCHAR2(20 BYTE)           NOT NULL,
  DAT_CADASTRO      DATE                        NOT NULL,
  DMN_FL_BLOQ       VARCHAR2(1 BYTE)            DEFAULT 'N'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ATB_FORNECEDOR_MATERIAL
(
  SEQ_FORNECEDOR     NUMBER(9)                  NOT NULL,
  SEQ_MATERIAL       NUMBER(10)                 NOT NULL,
  DAT_CADASTRO       DATE                       NOT NULL,
  NOM_USUARIO        VARCHAR2(20 BYTE)          NOT NULL,
  QTD_MAXIMA_COMPRA  NUMBER(5,2)                NOT NULL,
  VAL_PRECO_MAXIMO   NUMBER(10,2)               NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX FORNECEDOR_MAT_PK ON ATB_FORNECEDOR_MATERIAL
(SEQ_FORNECEDOR, SEQ_MATERIAL)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX FORNECEDOR_PK ON ATB_FORNECEDOR
(SEQ_FORNECEDOR)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX MATERIAL_PK ON ATB_MATERIAL
(SEQ_MATERIAL)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ATB_REQUISICAO_PK ON ATB_REQUISICAO
(NUM_REQUISICAO)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX FORNECEDOR_ENDERECO_PK ON ATB_FORNECEDOR_ENDERECO
(SEQ_FORNECEDOR, DM_TPO_ENDERECO)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ATB_NFE_ITEM_PK ON ATB_NOTA_ENTRADA_ITEM
(SEQ_FORNECEDOR, NUM_NOTA, SEQ_ITEM)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX ATB_NOTA_ENTRADA_PK ON ATB_NOTA_ENTRADA
(SEQ_FORNECEDOR, NUM_NOTA)
LOGGING
NOPARALLEL;


ALTER TABLE ATB_NOTA_ENTRADA_ITEM ADD (
  CONSTRAINT ATB_NFE_ITEM_PK
 PRIMARY KEY
 (SEQ_FORNECEDOR, NUM_NOTA, SEQ_ITEM));

ALTER TABLE ATB_FORNECEDOR_ENDERECO ADD (
  CONSTRAINT FORNECEDOR_ENDERECO_PK
 PRIMARY KEY
 (SEQ_FORNECEDOR, DM_TPO_ENDERECO));

ALTER TABLE ATB_REQUISICAO ADD (
  CONSTRAINT ATB_REQUISICAO_PK
 PRIMARY KEY
 (NUM_REQUISICAO));

ALTER TABLE ATB_NOTA_ENTRADA ADD (
  CONSTRAINT ATB_NOTA_ENTRADA_PK
 PRIMARY KEY
 (SEQ_FORNECEDOR, NUM_NOTA));

ALTER TABLE ATB_MATERIAL ADD (
  CONSTRAINT AVCON_1607021430_DMN_F_000
 CHECK (DMN_FL_BLOQ IN ('N', 'S')),
  CONSTRAINT MATERIAL_PK
 PRIMARY KEY
 (SEQ_MATERIAL));

ALTER TABLE ATB_FORNECEDOR ADD (
  CONSTRAINT AVCON_1607021430_DMN_F_001
 CHECK (DMN_FL_BLOQ IN ('N', 'S')),
  CONSTRAINT FORNECEDOR_PK
 PRIMARY KEY
 (SEQ_FORNECEDOR));

ALTER TABLE ATB_FORNECEDOR_MATERIAL ADD (
  CONSTRAINT FORNECEDOR_MAT_PK
 PRIMARY KEY
 (SEQ_FORNECEDOR, SEQ_MATERIAL));

ALTER TABLE ATB_REQUISICAO_ITEM ADD (
  CONSTRAINT ARM_MAL_FK 
 FOREIGN KEY (SEQ_MATERIAL) 
 REFERENCES ATB_MATERIAL (SEQ_MATERIAL),
  CONSTRAINT ARM_ARO_FK 
 FOREIGN KEY (NUM_REQUISICAO) 
 REFERENCES ATB_REQUISICAO (NUM_REQUISICAO));

ALTER TABLE ATB_NOTA_ENTRADA_ITEM ADD (
  CONSTRAINT ANM_MAL_FK 
 FOREIGN KEY (SEQ_MATERIAL) 
 REFERENCES ATB_MATERIAL (SEQ_MATERIAL),
  CONSTRAINT ANM_ANA_FK 
 FOREIGN KEY (SEQ_FORNECEDOR, NUM_NOTA) 
 REFERENCES ATB_NOTA_ENTRADA (SEQ_FORNECEDOR,NUM_NOTA));

ALTER TABLE ATB_FORNECEDOR_ENDERECO ADD (
  CONSTRAINT FEO_FRN_FK 
 FOREIGN KEY (SEQ_FORNECEDOR) 
 REFERENCES ATB_FORNECEDOR (SEQ_FORNECEDOR));

ALTER TABLE ATB_NOTA_ENTRADA ADD (
  CONSTRAINT ANA_FRN_FK 
 FOREIGN KEY (SEQ_FORNECEDOR) 
 REFERENCES ATB_FORNECEDOR (SEQ_FORNECEDOR));

ALTER TABLE ATB_FORNECEDOR_MATERIAL ADD (
  CONSTRAINT FML_FRN_FK 
 FOREIGN KEY (SEQ_FORNECEDOR) 
 REFERENCES ATB_FORNECEDOR (SEQ_FORNECEDOR),
  CONSTRAINT FML_MAL_FK 
 FOREIGN KEY (SEQ_MATERIAL) 
 REFERENCES ATB_MATERIAL (SEQ_MATERIAL));

